#!/usr/bin/env bash

set -ex

export DEBIAN_FRONTEND=noninteractive
echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02speedup
echo "man-db man-db/auto-update boolean false" | debconf-set-selections

BUILDDIR=/build
SCRIPTDIR=$(readlink -f "$(dirname "$0")")

cp -vr -- "$SCRIPTDIR" "$BUILDDIR"

cd "$BUILDDIR"

apt-get update && apt-get -y upgrade

apt-get install -y devscripts equivs

git clean -d -f

yes | mk-build-deps -i

./use-mpv-release
./use-ffmpeg-release
./update

sed -i 's/UNRELEASED/buster-backports/' ./debian/changelog

dpkg-buildpackage -uc -us -b -j2

cp -v -- ../*.{deb,changes} /output

exit 0
